language: python
python:
  - "3.6"
install:
- pip install -r requirements.txt
- pip install codecov
# command to run tests
script: 
- pytest --cov=./good_smell 
after_success:
  - codecov

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master
    tag: true